# This file was generated by GoReleaser. DO NOT EDIT.
cask "spillway" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "48eed1d5432679a33231f09bb9ce459d359f8b34cd4b387855d08f9cfa27198f"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c50504b048b7cf4697defbe879d55fe352da8f76684af4fb58d92bba2bfec400"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8202a53a25ba571b3c628bb86c4de3f639789ecc6cbcacff2987caad2865d837"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb031301024b85fbafa8626eb72819ca7a9c4daa686b71fc72b02394380c4a90"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "spillway"
  desc "Pool your own AI subscription accounts behind one local proxy"
  homepage "https://github.com/coderage-labs/spillway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spillway"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/spillway"

      if File.exist?("#{Dir.home}/Library/LaunchAgents/dev.coderage.spillway.plist")
        ohai "Restarting the spillway service on the new binary"
        system_command "#{HOMEBREW_PREFIX}/bin/spillway",
                       args: ["service", "install"],
                       must_succeed: false
      end
    end
  end

  zap launchctl: [
      "dev.coderage.spillway",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.coderage.spillway.plist",
      "~/Library/Logs/spillway.log",
    ]

end
