# This file was generated by GoReleaser. DO NOT EDIT.
cask "spillway" do
  version "0.23.1"

  on_macos do
    on_arm do
      sha256 "6b9d6b525014ef7e93bed3b7268f55eff08d59358e5eb1893d84f1c2cec143b3"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f02ac5e3b3ecce24286682e7191d1a33b2ad24174aa9692cf101f2e239947de5"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5d5b430010ece52ee36fe8d73123f19e6fc6ef0fd342b2411eca431f5869372c"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3990ada9575003ebac97d9a793e13cabbb62e7a6fb7c48ed291ae70ea3a81d61"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "spillway"
  desc "Pool your own AI subscription accounts behind one local proxy"
  homepage "https://github.com/coderage-labs/spillway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spillway"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/spillway"

      if File.exist?("#{Dir.home}/Library/LaunchAgents/dev.coderage.spillway.plist")
        ohai "Restarting the spillway service on the new binary"
        system_command "#{HOMEBREW_PREFIX}/bin/spillway",
                       args: ["service", "install"],
                       must_succeed: false
      end
    end
  end

  zap launchctl: [
      "dev.coderage.spillway",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.coderage.spillway.plist",
      "~/Library/Logs/spillway.log",
    ]

end
