# This file was generated by GoReleaser. DO NOT EDIT.
cask "spillway" do
  version "0.18.0"

  on_macos do
    on_arm do
      sha256 "38ac8685245c024ede0e5db5be3d7b01caccf8323832ca123c68d076aea06ed3"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c118814d8d53328c3bfeccd9b05d60cd1e029f1a9a1a10a766acaf07adad8432"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d77ff02fb74ca972a690a0a0d389b373f75c3d1286d582a0192afa6d8ca52558"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b7aba6b78169b906fd02d64ca509edf44975ab6fa3dcdd7dbb7f27f386e594a"
      url "https://github.com/coderage-labs/spillway/releases/download/v#{version}/spillway_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "spillway"
  desc "Pool your own AI subscription accounts behind one local proxy"
  homepage "https://github.com/coderage-labs/spillway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spillway"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/spillway"

      if File.exist?("#{Dir.home}/Library/LaunchAgents/dev.coderage.spillway.plist")
        ohai "Restarting the spillway service on the new binary"
        system_command "#{HOMEBREW_PREFIX}/bin/spillway",
                       args: ["service", "install"],
                       must_succeed: false
      end
    end
  end

  zap launchctl: [
      "dev.coderage.spillway",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.coderage.spillway.plist",
      "~/Library/Logs/spillway.log",
    ]

end
